### ISSUE TITLE
I have many questions and suggestions ...

### ISSUE THREAD

**Issue by Damnie** [faceofcat/Tesla-Powered-Thingies#8]
What is Fruit Picker? I put it on crop farm and I can't see something happened.

1:It's about advancements...
advancements.teslathingies:wrench.title=Wrench Everything!
advancements.teslathingies:wrench.description=No... this is not a mistyped wench... :(
It haven't done yet...I don't know the description about the below line. 
And the advancements.teslathingies.ore_processing.item and its description haven't the lang file...

2:Liquidxp Storage can be added any other fluid and the texture always is the liquidxp.
Picture 1:
![image](https://user-images.githubusercontent.com/28680836/30330022-7dc405d6-9806-11e7-8b72-07df1650d726.png)
Picture 2:
![image](https://user-images.githubusercontent.com/28680836/30330079-a3404306-9806-11e7-933d-2030b70c6446.png)

3.Powered Kiln 's JEI can't be opened.

4.Machine GUI's some words can't be edited by .lang file
Like Stored Energy, Open JEI and 
![image](https://user-images.githubusercontent.com/28680836/30330277-3654013c-9807-11e7-83e0-6673e62ecf90.png)
Energy, Charge Pad, Input Items, Output Items...
![image](https://user-images.githubusercontent.com/28680836/30330416-999d4cbc-9807-11e7-9648-cd7015613c96.png)
Always Active, Active on Redstone Signal...
Some like Fluids: , Empty, Lock Inventory , Unlock Inventory , waiting for a tree , Show work area

I know It's hard to rewrite it, but many people don't know English...So if you improve it I will appreciate it: ) , I don't mind it...

5.It's about texture...When I use the SEUS or Continuum, some machine textures are a little strange
Like this:
![image](https://user-images.githubusercontent.com/28680836/30330832-ba6d6e44-9808-11e7-9efe-73db20e0c075.png)
Machine Lists:
fluid_burner
fluid_solidifier
fluid_compound_producer
item_compound_producer
liquidxp_storage

I will always like this mod, and I wish it will shine one day.
And ... I'm a Chinese and my English is not well , forgive me :)

**Comment by faceofcat** [comment]
1. advancements are WIP... just ignore them for now :)

2. that's a good find... I'll make a separate issue about that and I'll get it fixed in next version

3. already fixed... will be in in next version

4. ok... not sure if next version of not... but I'll take care of it :)

5. I probably know why that happens... but really sure how to fix it... will put on list.

thanks!

**Comment by Damnie** [comment]
One more thing: I hope the Crop Farm can break the dirt block's grass(on it) directly.

**Comment by faceofcat** [comment]
oh... and Fruit Picker.... that's a weird one...

that is supposed to collect fruits from Pam's Fruit Trees planted inside the work area...

but I have no idea if Pam's is even out for 1.12... if if that addon still works... :)

**Comment by Damnie** [comment]
Hah, I think the addon aimed to pick tree's apple(in the tree farm) at first

**Comment by faceofcat** [comment]
hmm... should the Crop Farm break grass... as in... grass that grows on blocks?... like wild flowers, tall grass etc... or it should tile land without a hoe being provided?

**Comment by Damnie** [comment]
Just to break it or provide support for shear to pick them like the tree farm

**Comment by Damnie** [comment]
No hoe also can break them like tree farm...

**Comment by DeadSix27** [comment]
I have a question as well, is it possible to have many different crops being harvested ?
Example:
Crop Farmer and 5 types of different crops, you can lock the input inventory of 2 seed types, e.g carrot and wheat.. but as soon it harvests .. lets say beetroot, it will output its seeds and not replant them (as there is not a filter for it) and since there are only 3 filter slots and 1 is taken by a hoe most likely.. how would I do this? Outputting and then inputting and hoping it already planted the previously inputted seed seems kinda funky.. not to mention there are going to be more seeds and it will eventually just fill up with one type

What could fix this is making it just not break the crop, most crops can be right clicked to be harvested, like mystical crops or vanilla ones (and a lot of others), maybe add an option to let it do that? and fall back to destroying for ones that don't support it?

And is there a way to speed it up too? Upgrades maybe? I could not find any beside range

EDIT: All this is similar to how the Ender IO farming station used to work

**Comment by faceofcat** [comment]
it should accept energy and speed upgrades... (if for some reason they are not available in game, check tesla core lib config)

a hoe is not really needed... unless you live in a slime infested area and your farm land will get jumped on by those little bastards... :)

I'm actually kind of making that farm obsolete... and making a new Generic Farm machine that supports more upgrades for picking fruits, collecting bushes (natura, rustic etc)... I could add an addon to that that would use seeds from the output inventory... picking one at random... I guess that would allow you to have more than the maximum 3 types of seeds...

also... you could use the Crop Cloner thing ;)
